name: Docs

env:
  NODE_VERSION: 16.x

# Only one docs build may run at a time, so they don't clobber
# each others' work. This should be fine with the push frequency
# to the SDK repository.
concurrency: docs-build

on:
  push:
    branches: [wcauchois--api-docs] # TEMP while developing.

jobs:
  setup-and-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/checkout@v3
      - name: Install and build-docs-markdown
        run: |
          npm install
          npm run build-docs-markdown
      - uses: actions/upload-artifact@v3
        with:
          name: markdown
          path: docs-build/markdown

  build-html:
    needs: setup-and-markdown
    runs-on: ubuntu-latest
    container:
      # TODO: Figure out an image registry to use.
      image: wcauchois/ubuntu-pandoc
    steps:
      - uses: actions/checkout@v3
      - run: mkdir docs-build
      - uses: actions/download-artifact@v3
        with:
          name: markdown
          path: docs-build/markdown
      - run: bash scripts/buildDocsHtml.sh
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: docs-build/html

  update-github-pages:
    needs: build-html
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: html
          path: docs-build/html
      - name: Commit and push to gh-pages branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git ls-files | grep '\.html$' | xargs git rm
          cp -r docs-build/html/* ./
          git add .

          if ! (git diff --quiet && git diff --staged --quiet); then
            git commit -m "Automatic docs update"
            git push origin gh-pages
          else
            echo "No changes detected."
          fi
